export const blogs = [
    {
      id: 1,
      title: "Understanding JavaScript",
      description: "A comprehensive guide to understanding JavaScript concepts.",
      author: "John Doe",
      content: "JavaScript is a versatile language that powers most of the web applications today. It is used for both front-end and back-end development.",
      categories: ["Programming", "JavaScript"],
      publishedDate: "2024-11-10",
    },
    {
        id: 2,
      title: "Exploring TypeScript",
      description: "Learn how TypeScript enhances JavaScript.",
      author: "Jane Smith",
      content: "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. It offers static typing, better tooling, and robust codebases.",
      categories: ["Programming", "TypeScript"],
      publishedDate: "2024-11-12",
    },
    {
        id: 3,
      title: "React Best Practices",
      description: "Tips and tricks for building better React applications.",
      author: "Alice Johnson",
      content: "React is a powerful library for building user interfaces. Following best practices like component composition, hooks, and clean state management can elevate your React apps.",
      categories: ["Web Development", "React"],
      publishedDate: "2024-11-14",
    },
    {
        id: 4,
      title: "State Management in Redux Toolkit",
      description: "Simplify your state management with Redux Toolkit.",
      author: "Bob Brown",
      content: "Redux Toolkit simplifies the complexity of state management in React applications. It includes powerful tools like createSlice and createAsyncThunk.",
      categories: ["Web Development", "Redux"],
      publishedDate: "2024-11-15",
    },
    {
        id: 5,
      title: "Introduction to Next.js",
      description: "Learn the basics of Next.js for server-side rendering and more.",
      author: "Chris Green",
      content: "Next.js is a React framework that enables features like server-side rendering and static site generation, making it perfect for modern web development.",
      categories: ["Web Development", "Next.js"],
      publishedDate: "2024-11-16",
    },
    {
        id: 6,
      title: "Building Accessible Web Apps",
      description: "Ensure your web applications are accessible to everyone.",
      author: "Diana White",
      content: "Accessibility in web development is crucial. Implementing ARIA roles, semantic HTML, and proper color contrasts ensures inclusivity for all users.",
      categories: ["Web Development", "Accessibility"],
      publishedDate: "2024-11-17",
    },
  ];
  